# needed for StatefulSet
kind: Service
apiVersion: v1
metadata:
  name: shilp-csi-attacher-s3
  namespace: kube-system
  labels:
    app: shilp-csi-attacher-s3
spec:
  selector:
    app: shilp-csi-attacher-s3
  ports:
    - name: csi-s3-dummy
      port: 65535
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: shilp-csi-attacher-s3
  namespace: kube-system
spec:
  serviceName: shilp-csi-attacher-s3
  replicas: 1
  selector:
    matchLabels:
      app: shilp-csi-attacher-s3
  template:
    metadata:
      labels:
        app: shilp-csi-attacher-s3
    spec:
      serviceAccount: csi-attacher-sa
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: "Exists"
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v2.2.0
          args:
            - "--v=4"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/me.shilp.csi.s3-driver/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/me.shilp.csi.s3-driver
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/me.shilp.csi.s3-driver
            type: DirectoryOrCreate
