kind: Service
apiVersion: v1
metadata:
  name: shilp-csi-provisioner-s3
  namespace: kube-system
  labels:
    app: shilp-csi-provisioner-s3
spec:
  selector:
    app: shilp-csi-provisioner-s3
  ports:
    - name: csi-s3-dummy
      port: 65535
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: shilp-csi-provisioner-s3
  namespace: kube-system
spec:
  serviceName: shilp-csi-provisioner-s3
  replicas: 1
  selector:
    matchLabels:
      app: shilp-csi-provisioner-s3
  template:
    metadata:
      labels:
        app: shilp-csi-provisioner-s3
    spec:
      serviceAccount: csi-provisioner-sa
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: "Exists"
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v2.1.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=4"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/me.shilp.csi.s3-driver/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/me.shilp.csi.s3-driver
        - name: csi-s3
          image: shilpgupta/csi-s3:dev
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(NODE_ID)"
            - "--v=4"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/kubelet/plugins/me.shilp.csi.s3-driver/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/me.shilp.csi.s3-driver
      volumes:
        - name: socket-dir
          emptyDir: {}
